services:
  proof-server:
    image: 'ghcr.io/midnight-ntwrk/proof-server:6.1.0-alpha.5'
    container_name: proof-server_$TESTCONTAINERS_UID
    ports:
      - '6300'
    environment:
      RUST_BACKTRACE: 'full'
      EXTRA_ARGS: -v
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:6300/version']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
