version: '3.5'
services:
  proof-server:
    image: "ghcr.io/midnight-ntwrk/proof-server:2.0.7"
    command: ["midnight-proof-server --network undeployed"]
    ports:
      - "6300:6300"
    environment:
      RUST_BACKTRACE: "full"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6300/version" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  indexer:
    image: "ghcr.io/midnight-ntwrk/midnight-pubsub-indexer:1.1.2"
    ports:
      - "8088"
    command: ['-Dlogback.configurationFile=logback-json-file.xml']
    environment:
      OPERATION_MODE: 'indexer'
      LOG_LEVEL: 'TRACE'
      LEDGER_NETWORK_ID: 'Undeployed'
      SUBSTRATE_NODE_URL: 'node'
      SUBSTRATE_NODE_WS_URL: 'ws://node:9944'
      DB_VENDOR: 'postgresql'
      DB_URL: 'postgres:5432/pubsub-indexer'
      DB_USER: 'pubsub-indexer'
      DB_PASS: 'pubsub-indexer'
      REDIS_URL: 'tcp://redis:6379'
      OTEL_JAVAAGENT_ENABLED: 'false'
    healthcheck:
      test: ['CMD', 'egrep', '"Block .* was stored at height 0"', '/tmp/app_logs/server.log']
      interval: 1s
      timeout: 5s
      retries: 30
    depends_on:
      node:
        condition: service_started
      postgres:
        condition: service_started
      redis:
        condition: service_started
  pubsub:
    image: 'ghcr.io/midnight-ntwrk/midnight-pubsub-indexer:1.1.2'
    platform: linux/amd64
    expose: ['8088']
    ports:
      - '8088:8088'
    environment:
      OPERATION_MODE: 'pubsub'
      LOG_LEVEL: 'TRACE'
      LEDGER_NETWORK_ID: 'Undeployed'
      SUBSTRATE_NODE_URL: 'node'
      SUBSTRATE_NODE_WS_URL: 'ws://node:9944'
      DB_VENDOR: 'postgresql'
      DB_URL: 'postgres:5432/pubsub-indexer'
      DB_USER: 'pubsub-indexer'
      DB_PASS: 'pubsub-indexer'
      REDIS_URL: 'tcp://redis:6379'
      OTEL_JAVAAGENT_ENABLED: 'false'
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      indexer:
        condition: service_healthy
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'pubsub-indexer'
      POSTGRES_PASSWORD: 'pubsub-indexer'
      POSTGRES_DB: 'pubsub-indexer'
  redis:
    image: redis:7.2.4
    ports:
      - 6379:6379
  node:
    image: "ghcr.io/midnight-ntwrk/midnight-node:0.3.1-2fdca2b"
    platform: linux/amd64
    ports:
     - "9944:9944"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9944/health" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      RUN_DEV_NET: "TRUE"
