services:
  proof-server:
    image: registry.ci.iog.io/proof-server:master
    container_name: proof-server_$TESTCONTAINERS_UID
    ports:
      - '0:6300'
  node:
    image: 596662952274.dkr.ecr.eu-north-1.amazonaws.com/mn:node-a608c355b9474231becb3693ce8923e5a69eb01e
    container_name: node_$TESTCONTAINERS_UID
    environment:
      - RUN_DEV_NET=TRUE
    ports:
      - '0:9933'
      - '0:9944'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9933/health" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 40s
  indexer:
    image: ghcr.io/input-output-hk/midnight-pubsub-indexer:556b2bf03cf9d353a9631b8f76510b9cf5b727ac
    container_name: indexer_$TESTCONTAINERS_UID
    ports:
      - '0:8088'
    command: ["midnight-pubsub-indexer", "-Devents-source.node-host=node"]
    environment:
      - SUBSTRATE_NODE_URL=node
    depends_on:
      node:
        condition: service_healthy
