services:
  proof-server:
    image: ghcr.io/midnight-ntwrk/proof-server:3.0.0
    container_name: proof-server_$TESTCONTAINERS_UID
    command: ["midnight-proof-server --network $NETWORK_ID"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6300/health" ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - '0:6300'
