services:
  proof-server:
    image: ghcr.io/midnight-ntwrk/proof-server:latest
    container_name: proof-server_$TESTCONTAINERS_UID
    ports:
      - '0:6300'
  node:
    image: ghcr.io/midnight-ntwrk/midnight-node:latest
    container_name: node_$TESTCONTAINERS_UID
    environment:
      - RUN_DEV_NET=TRUE
    ports:
      - '0:9933'
      - '0:9944'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9933/health" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 40s
  indexer:
    image: ghcr.io/midnight-ntwrk/midnight-pubsub-indexer:latest
    container_name: indexer_$TESTCONTAINERS_UID
    ports:
      - '0:8088'
    command: ["midnight-pubsub-indexer", "-Devents-source.node-host=node"]
    environment:
      - SUBSTRATE_NODE_URL=node
    depends_on:
      node:
        condition: service_healthy
