services:
  proof-server:
    image: ghcr.io/midnight-ntwrk/proof-server:2.0.7
    container_name: proof-server
    ports:
      - '6300:6300'
  node:
    image: ghcr.io/midnight-ntwrk/midnight-node:0.2.2-7eff47a
    container_name: node
    environment:
      - RUN_DEV_NET=TRUE
    ports:
      - '9944:9944'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9944/health" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 40s
  indexer:
    image: ghcr.io/midnight-ntwrk/midnight-pubsub-indexer:1.0.11
    container_name: indexer
    ports:
      - '8088:8088'
    command: ["midnight-pubsub-indexer", "-Devents-source.node-http-url=http://node:9944", "-Devents-source.node-ws-url=ws://node:9944"]
    environment:
      LEDGER_NETWORK_ID: 'Undeployed'
      OTEL_JAVAAGENT_ENABLED: 'false'
    depends_on:
      node:
        condition: service_healthy
