services:
  proof-server:
    image: "ghcr.io/midnight-ntwrk/proof-server:4.0.0"
    container_name: proof-server_$TESTCONTAINERS_UID
    command: ["midnight-proof-server -v --network undeployed"]
    ports:
      - "6300"
    environment:
      RUST_BACKTRACE: "full"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6300/version" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  indexer:
    image: "ghcr.io/midnight-ntwrk/indexer-standalone:2.1.0"
    container_name: indexer_$TESTCONTAINERS_UID
    ports:
      - "8088"
    environment:
      LOG_LEVEL: 'TRACE'
      APP__INFRA__NODE__URL: "ws://node:9944"
      OTEL_JAVAAGENT_ENABLED: 'false'
      APP__APPLICATION__NETWORK_ID: 'Undeployed'
      APP__INFRA__SECRET: '822D8FFFEB8EC5CB2B52305C5F70197035089EB76505CD489BE18F4ADF8181D4D3'
      RUST_LOG: "indexer=debug,chain_indexer=debug,indexer_api=debug,wallet_indexer=debug,indexer_common=debug,info"
    healthcheck:
      test: ["CMD-SHELL", "cat /var/run/indexer-standalone/running"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      node:
        condition: service_started
  node:
    image: "ghcr.io/midnight-ntwrk/midnight-node:0.12.0"
    container_name: node_$TESTCONTAINERS_UID
    ports:
     - "9944"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9944/health" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      CFG_PRESET: "dev"
      SIDECHAIN_BLOCK_BENEFICIARY: "04bcf7ad3be7a5c790460be82a713af570f22e0f801f6659ab8e84a52be6969e"
