services:
  proof-server:
    image: ghcr.io/midnight-ntwrk/proof-server:2.0.7
    container_name: proof-server_$TESTCONTAINERS_UID
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6300/health" ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - '0:6300'
  node:
    image: ghcr.io/midnight-ntwrk/midnight-node:0c2efadf915b6b0dcd0d362400eb9aa3a3f4253b
    container_name: node_$TESTCONTAINERS_UID
    environment:
      - RUN_DEV_NET=TRUE
    ports:
      - '0:9944'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9944/health" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 40s
  indexer:
    image: ghcr.io/midnight-ntwrk/midnight-pubsub-indexer:1.0.5
    container_name: indexer_$TESTCONTAINERS_UID
    ports:
      - '0:8088'
    command: ["midnight-pubsub-indexer", "-Devents-source.node-http-url=http://node:9944", "-Devents-source.node-ws-url=ws://node:9944"]
    environment:
      LEDGER_NETWORK_ID: 'Undeployed'
      OTEL_JAVAAGENT_ENABLED: 'false'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8088/health" ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      node:
        condition: service_healthy
