version: '3.5'
services:
  proof-server:
    image: "ghcr.io/midnight-ntwrk/proof-server:3.0.0-beta.2"
    container_name: proof-server_$TESTCONTAINERS_UID
    command: ["midnight-proof-server --network undeployed"]
    ports:
      - "6300"
    environment:
      RUST_BACKTRACE: "full"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6300/version" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  indexer:
    image: "ghcr.io/midnight-ntwrk/midnight-pubsub-indexer:2.0.0-RC2"
    container_name: indexer_$TESTCONTAINERS_UID
    ports:
      - "8088"
    command: ['-Dlogback.configurationFile=logback-json-file.xml']
    environment:
      LOG_LEVEL: 'TRACE'
      LEDGER_NETWORK_ID: 'Undeployed'
      SUBSTRATE_NODE_WS_URL: 'ws://node:9944'
      OTEL_JAVAAGENT_ENABLED: 'false'
    healthcheck:
      test: ['CMD', 'egrep', '"Block .* was stored at height 0"', '/tmp/app_logs/server.log']
      interval: 1s
      timeout: 5s
      retries: 30
    depends_on:
      node:
        condition: service_started
  node:
    image: "ghcr.io/midnight-ntwrk/midnight-node:0.5.1-559a6836"
    platform: linux/amd64
    container_name: node_$TESTCONTAINERS_UID
    ports:
      - "9944"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9944/health" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      CFG_PRESET: "dev"
      ARGV: "midnight-node --rpc-external --rpc-cors=all --dev --node-key 0000000000000000000000000000000000000000000000000000000000000001"
