name: Healthcheck - Devnet

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  test:
    name: Healthcheck tests
    uses: ./.github/workflows/e2e-tests.yml
    with:
      network: devnet
      deployment: devnet
      modifier: '-t @healthcheck'
    secrets: inherit
